services:
  mysql:
    extends:
      file: docker-compose.yml
      service: mysql
    networks:
      - backend_network

  cache:
    extends:
      file: docker-compose.yml
      service: cache
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend_network

  etcd:
    extends:
      file: ./src/Database/VectorDB/docker-compose.yml
      service: etcd
    networks:
      - backend_network

  minio:
    extends:
      file: ./src/Database/VectorDB/docker-compose.yml
      service: minio
    networks:
      - backend_network

  milvus:
    extends:
      file: ./src/Database/VectorDB/docker-compose.yml
      service: standalone
    networks:
      - backend_network

  mq:
    extends:
      file: docker-compose.yml
      service: mq
    networks:
      - backend_network
  notify_mail_sender:
    extends:
      file: docker-compose.yml
      service: notify_mail_sender
    networks:
      - backend_network
volumes:
  dengta_mysql_volume:
    name: ${MYSQL_VOLUME_PATH}
  dengta_milvus_etcd_volume:
    name: ${MILVUS_ETCD_VOLUME_PATH}
  dengta_milvus_minio_volume:
    name: ${MILVUS_MINIO_VOLUME_PATH}
  dengta_milvus_volume:
    name: ${MILVUS_VOLUME_PATH}
  dengta_mq_volume:
    name: ${MQ_VOLUME_PATH}

networks:
  backend_network:
    name: dengta_backend_ci_network
