services:
  dengta_backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CUSTOM_ENV: ${CUSTOM_ENV}
    container_name: dengta_backend_container
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
      - INFISICAL_ENVIRONMENT=${INFISICAL_ENVIRONMENT}
    networks:
      - backend_network
    depends_on:
      mysql:
        condition: service_healthy
      milvus:
        condition: service_healthy
    ports:
      - ${BACKEND_PORT}:3001

  mysql:
    image: mysql:8.0.36-debian
    container_name: ${MYSQL_CONTAINER_NAME}
    platform: linux/amd64
    stdin_open: true
    tty: true
    restart: unless-stopped
    working_dir: /var/lib/mysql
    command: --bind-address=0.0.0.0
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - dengta_mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "mysqladmin ping -h localhost -u${MYSQL_USER} -p${MYSQL_PASSWORD} && mysql -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'show databases;'",
        ]
      timeout: 25s
      retries: 10
    networks:
      - backend_network

  cache:
    build:
      context: ./src/Database/Cache
    container_name: ${REDIS_CONTAINER_NAME}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - type: tmpfs
        target: /data
    networks:
      - backend_network

  etcd:
    extends:
      file: ./src/Database/VectorDB/docker-compose.yml
      service: etcd
    networks:
      - backend_network

  minio:
    extends:
      file: ./src/Database/VectorDB/docker-compose.yml
      service: minio
    networks:
      - backend_network

  milvus:
    extends:
      file: ./src/Database/VectorDB/docker-compose.yml
      service: standalone
    networks:
      - backend_network
volumes:
  dengta_mysql_volume:
    name: ${MYSQL_VOLUME_PATH}
  dengta_milvus_etcd_volume:
    name: ${MILVUS_VOLUME_PATH}_etcd
  dengta_milvus_minio_volume:
    name: ${MILVUS_VOLUME_PATH}_minio
  dengta_milvus_volume:
    name: ${MILVUS_VOLUME_PATH}

networks:
  backend_network:
    external: true
    name: dengta_backend_network
