version: '3.8'

services:
  dengta_backend:
    build:
      context: .
      # args:
      #     INFISICAL_ENVIRONMENT: ${INFISICAL_ENVIRONMENT}
      dockerfile: Dockerfile
    container_name: dengta_backend_container
    environment:
      - INFISICAL_TOKEN=${INFISICAL_TOKEN}
      - INFISICAL_ENVIRONMENT=${INFISICAL_ENVIRONMENT}
    networks:
      - backend_network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    extends:
      file: docker-compose-dev.yml
      service: mysql

  cache:
    build:
      context: ./src/Database/Cache
    container_name: ${REDIS_CONTAINER_NAME}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - type: tmpfs
        target: /data
    networks:
      - backend_network




volumes:
  dengta_mysql_volume:
    name: ${MYSQL_VOLUME_PATH}

networks:
  backend_network:
    external:
      name: dengta_backend_network