version: '3.8'

services:

  dengta_backend:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: dengta_backend_container
      env_file:
        - .env
      networks:
        - dengta_network

  db_production:
    image: mysql:8.0.36-debian
    container_name: mysql-production
    stdin_open: true
    tty: true
    restart: always
    working_dir: /var/lib/mysql
    ports:
      - "3309:3306"
    volumes:
      - /srv/dengta/dengta-file/production-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    networks:
      - dengta_network
      
  # redis:
  #   image: redis
  #   container_name: redis_container
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - dengta_network

  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./private/mergedCert.crt:/etc/ssl/certs/mergedCert.crt
  #     - ./private/private.key:/etc/ssl/certs/private.key
  #   networks:
  #     - inklinker_network
  #   depends_on:
  #     - inklinker_backend

networks:
  dengta_network:   
