services:
  dengta_backend:
    extends:
      # Note that the path of the Dockerfile and context is relative to the
      # *primary* docker-compose.yml file (the first in the devcontainer.json
      # "dockerComposeFile" array).
      file: ../docker-compose.yml
      service: dengta_backend
    build: .
    container_name: 'dengta_backend_devcontainer'
    environment: !reset [] # remove all environment variables and set as empty array
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
      milvus:
        condition: service_healthy

  mysql:
    extends:
      file: ../docker-compose-dev.yml
      service: mysql

  cache:
    extends:
      file: ../docker-compose-dev.yml
      service: cache

  etcd:
    extends:
      file: ../docker-compose-dev.yml
      service: etcd
    networks:
      - backend_network

  minio:
    extends:
      file: ../docker-compose-dev.yml
      service: minio
    networks:
      - backend_network

  milvus:
    extends:
      file: ../docker-compose-dev.yml
      service: milvus
    networks:
      - backend_network

volumes:
  dengta_mysql_volume:
    name: ${MYSQL_VOLUME_PATH}
  dengta_milvus_etcd_volume:
    name: ${MILVUS_VOLUME_PATH}_etcd
  dengta_milvus_minio_volume:
    name: ${MILVUS_VOLUME_PATH}_minio
  dengta_milvus_volume:
    name: ${MILVUS_VOLUME_PATH}

networks:
  backend_network:
    name: dengta_backend_network
