#!/bin/bash
# chkconfig: 2345 20 80
# description: Socat Port Forwarding for Multiple Services

SERVICES=(
    "6379 cache 6379 Redis"
    "3309 mysql 3306 MySQL"
    "19530 milvus 19530 Milvus-gRPC"
    "9091 milvus 9091 Milvus-HTTP"
    "9001 minio 9001 Minio-API"
    "9002 minio 9000 Minio-Console"
    "5001 embeddings_server 5001 embeddings-server"
    # Add more services as needed in the format "local_port remote_host remote_port friendly_name"
)

LOGDIR=/tmp/socat_logs
PIDDIR=/tmp/socat_pids
mkdir -p $LOGDIR $PIDDIR

case "$1" in
    start)
        echo "Starting Socat Port Forwarding for all services..."
        for SERVICE in "${SERVICES[@]}"; do
            IFS=' ' read -r LOCAL_PORT REMOTE_HOST REMOTE_PORT FRIENDLY_NAME <<< "$SERVICE"
            LOGFILE=$LOGDIR/socat_$FRIENDLY_NAME.log
            PIDFILE=$PIDDIR/socat_$FRIENDLY_NAME.pid

            echo "Starting Socat Port Forwarding for $FRIENDLY_NAME..."

            while ! nc -zw 10 $REMOTE_HOST $REMOTE_PORT
            do
                echo "Can't connect to $REMOTE_HOST:$REMOTE_PORT"
                sleep 2
            done

            while :
            do
                /usr/bin/nohup /usr/bin/socat -d -lf $LOGFILE TCP4-LISTEN:$LOCAL_PORT,bind=127.0.0.1,reuseaddr,fork TCP4:$REMOTE_HOST:$REMOTE_PORT >/dev/null 2>&1 &
                echo $! > $PIDFILE
                sleep 2
                if nc -zw 10 localhost $LOCAL_PORT; then
                    echo "Started Socat Port Forwarding for $FRIENDLY_NAME"
                    break
                else
                    echo "Failed to start Socat Port Forwarding for $FRIENDLY_NAME. Retrying..."
                    kill `cat $PIDFILE`
                    rm $PIDFILE
                fi
            done
        done
        echo "Started Socat Port Forwarding for all services"
    ;;
    stop)
        echo "Stopping Socat Port Forwarding for all services..."
        for SERVICE in "${SERVICES[@]}"; do
            IFS=' ' read -r LOCAL_PORT REMOTE_HOST REMOTE_PORT FRIENDLY_NAME <<< "$SERVICE"
            PIDFILE=$PIDDIR/socat_$FRIENDLY_NAME.pid

            echo "Stopping Socat Port Forwarding for $FRIENDLY_NAME..."
            if [ -f $PIDFILE ]; then
                kill `cat $PIDFILE`
                rm $PIDFILE
                echo "Stopped Socat Port Forwarding for $FRIENDLY_NAME"
            else
                echo "PID file for $FRIENDLY_NAME not found. Is it running?"
            fi
        done
        echo "Stopped Socat Port Forwarding for all services"
    ;;
    status)
        for SERVICE in "${SERVICES[@]}"; do
            IFS=' ' read -r LOCAL_PORT REMOTE_HOST REMOTE_PORT FRIENDLY_NAME <<< "$SERVICE"
            PIDFILE=$PIDDIR/socat_$FRIENDLY_NAME.pid

            if [ -f $PIDFILE ]; then
                if ps -p `cat $PIDFILE` > /dev/null; then
                    echo "Socat Port Forwarding for $FRIENDLY_NAME is running."
                else
                    echo "Process not found for $FRIENDLY_NAME, but PID file exists. It's PID was `cat $PIDFILE`"
                    rm $PIDFILE
                    exit 1
                fi
            else
                echo "Socat Port Forwarding for $FRIENDLY_NAME is not running."
                exit 3
            fi
        done
        echo "Socat Port Forwarding for all services are running."
    ;;
    *)
        echo "Usage: /etc/init.d/socat {start|stop|status}"
        exit 2
    ;;
esac

exit 0