#!/bin/bash
# chkconfig: 2345 20 80
# description: Socat Cache Port Forwarding

PIDFILE=/tmp/socat_cache.pid
LOGFILE=/tmp/socat_cache.log

case "$1" in
    start)
        echo "Starting Socat Cache Port Forwarding..."
        while ! nc -zw 10 cache 6379
        do
            echo "Can't connect to cache:6379"
            sleep 2
        done
        while :
        do
            /usr/bin/nohup /usr/bin/socat -d -lf $LOGFILE TCP4-LISTEN:6379,bind=127.0.0.1,reuseaddr,fork TCP4:cache:6379 >/dev/null 2>&1 &
            echo $! > $PIDFILE
            sleep 2
            if nc -zw 10 localhost 6379; then
                echo "Started Socat Cache Port Forwarding"
                break
            else
                echo "Failed to start Socat Cache Port Forwarding. Retrying..."
                kill `cat $PIDFILE`
                rm $PIDFILE
            fi
        done
    ;;
    stop)
        echo "Stopping Socat Cache Port Forwarding..."
        if [ -f $PIDFILE ]; then
            kill `cat $PIDFILE`
            rm $PIDFILE
        else
            echo "PID file not found. Is socat_cache running?"
            exit 1
        fi
    ;;
    status)
        if [ -f $PIDFILE ]; then
            if ps -p `cat $PIDFILE` > /dev/null; then
                echo "Socat Cache Port Forwarding is running."
            else
                echo "Process not found, but PID file exists. It's PID was `cat $PIDFILE`"
                rm $PIDFILE
                exit 1
            fi
        else
            echo "Socat Cache Port Forwarding is not running."
            exit 3
        fi
    ;;
    *)
        echo "Usage: /etc/init.d/socat_cache {start|stop|status}"
        exit 2
    ;;
esac

exit 0