name: Dengta Backend CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - "dev"

env:
  DEPLOY_ACCOUNT: githubactions
  SERVER_HOST: backend.dengta.org

jobs:
  deploy:
    runs-on: [self-hosted, dengta-ubuntu]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Move code to /srv
        run: |
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S rm -rf /srv/dengta-backend-development
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S mkdir -p /srv/dengta-backend-development
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S cp -r ./* /srv/dengta-backend-development

      - name: scp .env.production to server
        run: |
          echo "${{ secrets.COMPOSE_ENV_FILE_DEV }}" > .env.development
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S cp .env.development /srv/dengta-backend-development/.env.development
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S chown -R $USER:$USER /srv/dengta-backend-development

      - name: Update Docker Containers and Images
        run: |
          docker compose -f /srv/dengta-backend-development/docker-compose.yml down
          docker compose -f /srv/dengta-backend-development/docker-compose.yml --env-file /srv/dengta-backend-development/.env.development up --build -d