name: Dengta Backend CI

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_call: # 可以被其他 workflow 呼叫

env:
  DEPLOY_ACCOUNT: githubactions
  SERVER_HOST: backend.dengta.org

jobs:
  run-test:
    runs-on: [self-hosted, dengta-ubuntu]
    env:
      INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Move code to /srv
        run: |
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S rm -rf /srv/dengta-ci
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S mkdir -p /srv/dengta-ci
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S cp -r ./* /srv/dengta-ci
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S chown -R $USER:$USER /srv/dengta-ci
      - name: scp .env.dev to server
        run: |
          echo "${{ secrets.COMPOSE_ENV_FILE_CI }}" > .env.staging
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S cp .env.staging /srv/dengta-ci/.env.staging
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S chown -R $USER:$USER /srv/dengta-ci
      - name: run the container test needs
        run: |
          docker compose -f /srv/dengta-ci/docker-compose-ci.yml down -v
          docker compose -f /srv/dengta-ci/docker-compose-ci.yml --env-file /srv/dengta-ci/.env.staging up --build -d
      - name: Wait for MySQL to be Ready
        run: |
          wget -O wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
          chmod +x wait-for-it.sh
          ./wait-for-it.sh mysql_staging:3309 --timeout=300 --strict
      - name: Wait for Milvus to be Ready
        run: |
          ./wait-for-it.sh milvus-standalone-staging:19533 --timeout=300 --strict
      - name: Install
        run: |
          cd /srv/dengta-ci
          npm install --force
      - name: Run tests
        run: |
          cd /srv/dengta-ci
          npm test
      - name: Send Notification to Discord
        if: success()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: 'GitHub Bot'
          message: |
            **[Test]** Tests completed. The **「${{ github.event_name }}」** event triggered by **「${{ github.actor }}」** on **${{ github.ref }}** succeeded.
      - name: Send Notification to Discord
        if: failure()
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: 'GitHub Bot'
          message: |
            **[Test]** Tests completed,but failed. The **「${{ github.event_name }}」** event triggered by **「${{ github.actor }}」** on **${{ github.ref }}** failed.
