name: Dengta Backend CI

on:
  pull_request:
    branches:
      - main
      - develop
  workflow_call: # 可以被其他 workflow 呼叫

env:
  DEPLOY_ACCOUNT: githubactions
  SERVER_HOST: backend.dengta.org

jobs:
  run-test:
    runs-on: [self-hosted, dengta-ubuntu]
    env:
      INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Move code to /srv
        run: |
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S rm -rf /srv/dengta-ci
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S mkdir -p /srv/dengta-ci
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S cp -r ./* /srv/dengta-ci
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S chown -R $USER:$USER /srv/dengta-ci
      - name: scp .env.dev to server
        run: |
          echo "${{ secrets.COMPOSE_ENV_FILE_CI }}" > .env.staging
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S cp .env.staging /srv/dengta-ci/.env.staging
          echo "${{ secrets.GITHUBACTIONS_USER_PASSWD }}" | sudo -S chown -R $USER:$USER /srv/dengta-ci
      - name: run the container test needs
        run: |
          docker compose -f /srv/dengta-ci/docker-compose-ci.yml down
          docker volume rm milvus-minio-staging milvus-staging dengta-mysql-staging
          docker compose -f /srv/dengta-ci/docker-compose-ci.yml --env-file /srv/dengta-ci/.env.staging up --build -d
      - name: Wait for Milvus and MySQL to be Ready
        run: |
          wait_for() {
            local host="$1"
            local port="$2"
            local timeout="$3"
            local start_time=$(date +%s)

            echo "等待 ${host}:${port} 啟動..."

            while true; do
              if nc -z "$host" "$port"; then
                echo "${host}:${port} 已啟動。"
                break
              fi

              current_time=$(date +%s)
              elapsed=$(( current_time - start_time ))

              if [ "$elapsed" -ge "$timeout" ]; then
                echo "等待 ${host}:${port} 超時 (${timeout} 秒)。"
                exit 1
              fi

              sleep 5
            done
          }

          wait_for localhost 19533 300
          wait_for localhost 3309 300
      - name: Install
        run: |
          cd /srv/dengta-ci
          npm install --force
      - name: Run tests
        run: |
          cd /srv/dengta-ci
          npm run test:ci

      - name: Discord success notification
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USERNAME: DengTa Chill Bot
          DISCORD_AVATAR: https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Chill_guy_original_artwork.jpg/220px-Chill_guy_original_artwork.jpg
        uses: Ilshidur/action-discord@master
        with:
          args: '✅ [CI] **API Test** from「**${{ github.event.pull_request.head.ref }}**」完美的成功了🥳'
      - name: Notify on fail
        if: failure()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USERNAME: DengTa Chill Bot
          DISCORD_AVATAR: https://upload.wikimedia.org/wikipedia/en/thumb/c/c7/Chill_guy_original_artwork.jpg/220px-Chill_guy_original_artwork.jpg
        uses: Ilshidur/action-discord@master
        with:
          args: '🚫 [CI] **API Test** from「**${{ github.event.pull_request.head.ref }}**」 完美的失敗了👺'
